# Generated by Django 2.0.4 on 2019-01-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField()),
                ('Image', models.ImageField(blank=True, null=True, upload_to='chapter/%Y/%m/%D/')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
