# Generated by Django 2.0.4 on 2019-01-08 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_auto_20190108_1414'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact1',
            new_name='Contact',
        ),
    ]
