# Generated by Django 2.0.4 on 2019-01-08 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_auto_20190108_1442'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About1',
            new_name='About',
        ),
        migrations.RenameModel(
            old_name='Contact1',
            new_name='Contact',
        ),
    ]
