# Generated by Django 2.0.4 on 2019-01-08 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_auto_20190108_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='pub_date',
        ),
    ]
