# Generated by Django 2.0.4 on 2019-02-04 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0016_auto_20190113_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='bgpa',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='blocation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='bmajor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='buniversity',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='about',
            name='mgpa',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='mlocation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='mmajor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='muniversity',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
