# Generated by Django 2.0.4 on 2019-02-04 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0017_auto_20190204_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='slide',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='blog',
            name='github',
            field=models.URLField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='language',
            field=models.TextField(null=True),
        ),
    ]
