# Generated by Django 2.0.4 on 2019-02-04 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0018_auto_20190204_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='github',
            field=models.URLField(max_length=150),
        ),
        migrations.AlterField(
            model_name='blog',
            name='language',
            field=models.TextField(),
        ),
    ]
