# Generated by Django 2.0.4 on 2019-02-04 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0019_auto_20190204_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='github',
            new_name='git',
        ),
    ]
