# Generated by Django 2.0.4 on 2019-02-04 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0020_auto_20190204_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='language',
            field=models.TextField(null=True),
        ),
    ]
