# Generated by Django 2.0.4 on 2019-02-04 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0022_auto_20190204_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='git',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='languag',
        ),
    ]
