# Generated by Django 2.0.4 on 2019-02-04 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0024_auto_20190204_2346'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('by', models.CharField(max_length=50)),
                ('link', models.URLField(max_length=150)),
                ('body', models.CharField(max_length=300, null=True)),
                ('gihub', models.URLField(max_length=150)),
                ('lang', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='git',
            new_name='gihub',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='languag',
            new_name='lang',
        ),
    ]
