# Generated by Django 2.0.4 on 2019-02-05 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0026_auto_20190204_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='github',
            field=models.URLField(blank=True, max_length=150, null=True),
        ),
    ]
