# Generated by Django 2.0.4 on 2019-02-05 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0027_auto_20190205_0001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='lang',
            new_name='language',
        ),
    ]
